# Generated by Django 2.0 on 2020-08-27 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20200827_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement_work_order_create',
            name='project_measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.project'),
        ),
    ]
