# Generated by Django 2.0 on 2020-09-06 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20200828_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure_values',
            name='measure_project',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='mysite.project'),
            preserve_default=False,
        ),
    ]
