# Generated by Django 2.0 on 2020-09-15 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_measure_values_measure_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure_items',
            name='measure_unit',
            field=models.CharField(choices=[('mm', 'mm'), ('in', 'in')], default=1, max_length=5),
            preserve_default=False,
        ),
    ]
