# Generated by Django 2.0 on 2020-09-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20200915_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='file_mgmt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('file', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
    ]
