# Generated by Django 2.0 on 2020-09-18 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_file_mgmt'),
    ]

    operations = [
        migrations.CreateModel(
            name='measure_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads')),
            ],
        ),
        migrations.DeleteModel(
            name='file_mgmt',
        ),
        migrations.AddField(
            model_name='measure_items',
            name='measure_number',
            field=models.CharField(choices=[('1', '1'), ('3', '3'), ('5', '5'), ('7', '7')], default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measure_image',
            name='measure_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.measure_items'),
        ),
        migrations.AddField(
            model_name='measure_image',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.project'),
        ),
    ]
