# Generated by Django 2.0 on 2020-09-18 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_auto_20200918_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure_items',
            name='image',
            field=models.ImageField(default=1, upload_to='uploads/111'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='measure_image',
            name='image',
            field=models.ImageField(upload_to='uploads/111'),
        ),
    ]
