# Generated by Django 2.0 on 2020-09-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_measure_values_image_base64_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measure_values',
            name='image_base64_data',
        ),
        migrations.AddField(
            model_name='measure_items',
            name='image_base64_data',
            field=models.TextField(default=1, max_length=10000),
            preserve_default=False,
        ),
    ]
