# Generated by Django 2.0 on 2020-09-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_auto_20200924_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure_items',
            name='image_base64_data',
            field=models.TextField(blank=True, max_length=100000),
        ),
    ]
