# Generated by Django 2.0 on 2020-09-28 08:27

from django.db import migrations, models
import mysite.models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_auto_20200925_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure_items',
            name='image',
            field=models.ImageField(upload_to=mysite.models.upload_path_handler),
        ),
    ]
