# Generated by Django 2.0 on 2020-10-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_auto_20200928_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure_items',
            name='measure_points',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measure_values',
            name='measure_man',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measure_values',
            name='measure_number',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
