# Generated by Django 2.0 on 2020-10-16 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0016_auto_20201005_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure_values',
            name='measure_tool',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mysite.measuring_tool'),
            preserve_default=False,
        ),
    ]
