# Generated by Django 2.0 on 2020-11-27 12:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0017_measure_values_measure_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure_values',
            name='time_now',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
