# Generated by Django 2.0 on 2020-12-14 14:03

from django.db import migrations, models
import mysite.models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0022_auto_20201214_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.ImageField(upload_to=mysite.models.upload_path_handler_project),
        ),
    ]
